name: mrmt3
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy=1.23.5
  - protobuf=3.20.3
  - ffmpeg        # For audio file support
  - pip:
      - jax==0.4.13
      - jaxlib==0.4.13
      - flax
      - librosa==0.9.1
      - pretty-midi==0.2.9
      - note-seq==0.0.3
      - einops==0.4.1
      - hydra-core==1.2.0
      - tqdm
      - absl-py
      - pyyaml
      - typing_extensions
      - transformers==4.18.0      # Only needed if code uses HuggingFace models
      - torch                    # Only if repo uses PyTorch
      - t5==0.9.3                # Only if repo/code imports t5
      - ddsp==3.3.4              # Only if code needs Google's DDSP (add if unsure)
      - tensorflow==2.11         # Only if needed for utility scripts (not for JAX)
      - tensorflow-text==2.11
      - tensorflow_probability==0.19.0
      - torchaudio    # Only if needed for utility scripts
      - pytorch_lightning
      - pyglove==0.4.4
